export const COUNTRIESNAMES = [
    "Afghanistan", 
    "Argentina", 
    "Australia", 
    "Austria", 
    "Bahamas", 
    "Belgium", 
    "Belize", 
    "Brazil", 
    "British Virgin Islands",
    "Brunei",
    "Bulgaria",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Caribbean Netherlands",
    "Channel Islands",
    "Chile",
    "China",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Cyprus",
    "Czechia",
    "Denmark",
    "Ecuador",
    "Egypt",
    "Ethiopia",
    "Finland",
    "France",
    "Georgia",
    "Germany",
    "Greenland",
    "Haiti",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kenya",
    "Malaysia",
    "Maldives",
    "Mexico",
    "Monaco",
    "Mongolia",
    "Netherlands",
    "New Zealand",
    "Nigeria",
    "Norway",
    "Pakistan",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "S. Korea",
    "Saudi Arabia",
    "Serbia",
    "Singapore",
    "Slovakia",
    "South Africa",
    "Spain",
    "Sweden",
    "Switzerland",
    "Taiwan",
    "Thailand",
    "Turkey",
    "UAE",
    "UK",
    "Ukraine",
    "Uzbekistan",
    "Vietnam",
    "Zambia",
    "Zimbabwe",
]